from unittest import TestCase

from app.exceptions.exceptions import InvalidTokenException
from app.services.google_auth_service import GoogleAuthService


class TestGoogleAuthService(TestCase):
    def setUp(self) -> None:
        self.google_auth_service = GoogleAuthService()

    def test_validate_token(self):
        token = "eyJhbGciOiJSUzI1NiIsImtpZCI6ImIxYTgyNTllYjA3NjYwZWYyMzc4MWM4NWI3ODQ5YmZhMGExYzgwNmMiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJhY2NvdW50cy5nb29nbGUuY29tIiwiYXpwIjoiMjc2MTgzMTE4ODIzLXJoYmlwaGVwYTliczNic2kwNG1saXFuNWluYnA1bmxlLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tIiwiYXVkIjoiMjc2MTgzMTE4ODIzLXJoYmlwaGVwYTliczNic2kwNG1saXFuNWluYnA1bmxlLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tIiwic3ViIjoiMTAxMDIyMTE0NDMwNTAwMDAzMTY4IiwiaGQiOiJ1bmFsLmVkdS5jbyIsImVtYWlsIjoiYW5kZ29uemFsZXpjYXNAdW5hbC5lZHUuY28iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiYXRfaGFzaCI6ImMyTWJuTDNhT19uWkFnakZBWDFld2ciLCJuYW1lIjoiQ2FtaWxvIEFuZHJlcyBHb256YWxleiBDYXN0cm8iLCJwaWN0dXJlIjoiaHR0cHM6Ly9saDMuZ29vZ2xldXNlcmNvbnRlbnQuY29tL2EtL0FPaDE0R2lTU1F0dVozOF9TSEphdGxpS2VkemExR29JX0FfVVZpZERLVGRhd3c9czk2LWMiLCJnaXZlbl9uYW1lIjoiQ2FtaWxvIEFuZHJlcyIsImZhbWlseV9uYW1lIjoiR29uemFsZXogQ2FzdHJvIiwibG9jYWxlIjoiZXMiLCJpYXQiOjE2NTI2NDcyNDIsImV4cCI6MTY1MjY1MDg0MiwianRpIjoiMmZjNjkzZDVjZjhjODdjOTgwMGZkZTg4MThmMzFhZDc5N2VmMzVkYSJ9.mMlNtDxZ_xoQkGQOWwgiesvx8SbbPMxcSLcI-cEKMJaY3wqcSQmTT6a4-MqGLakyT44MfVx-pSeeEm7avydWSnV9Nw0VB0YsujpD8tqei-NR0RjQH4KDmmlVLdsMTDc8nsX_055qTabi0F8A7JO63za-sfhE8MKm3XeBcpWJMxe1yUVHGq7z2IsQIhYetISvlrHsBIBhNsgeV3ijEbK5_Tg62T6Rf7EHR9yiZECUv84irBM96WPrui8dCQOt2J4U7dl2nyz75B41L63kwtBIu3IM-Q-RWyxg8hOtcrniXIeEf8HBBxgpYkMflMbnU_QDb4aTjSzPQWUjIx4Z7h6vNQ"
        client_id = '101022114430500003168'
        self.assertRaises(InvalidTokenException, self.google_auth_service.validate_token, token, client_id)
